"""add api_key_id to checkout_sessions

Revision ID: 13d87b36157c
Revises: 1d80d997dc5b
Create Date: 2026-07-17 11:39:29.758435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13d87b36157c'
down_revision = '1d80d997dc5b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkout_sessions', sa.Column('api_key_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'checkout_sessions', 'api_keys', ['api_key_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'checkout_sessions', type_='foreignkey')
    op.drop_column('checkout_sessions', 'api_key_id')
    # ### end Alembic commands ###
