"""add subscriptions and saved payment methods

Revision ID: 1d80d997dc5b
Revises: 336a3cf553fe
Create Date: 2026-07-17 10:33:40.833378

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1d80d997dc5b'
down_revision = '336a3cf553fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_payment_methods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('method', sa.Enum('CARD', 'WALLET', name='saved_payment_method_type'), nullable=False),
    sa.Column('masked_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sandbox_digits', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('price_id', sa.UUID(), nullable=False),
    sa.Column('payment_method_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('INCOMPLETE', 'ACTIVE', 'PAST_DUE', 'CANCELED', 'UNPAID', name='subscription_status'), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('failed_attempt_count', sa.Integer(), nullable=False),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_method_id'], ['saved_payment_methods.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['price_id'], ['prices.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('invoices', sa.Column('subscription_id', sa.UUID(), nullable=True))
    op.add_column('invoices', sa.Column('billing_reason', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'invoices', 'subscriptions', ['subscription_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'billing_reason')
    op.drop_column('invoices', 'subscription_id')
    op.drop_table('subscriptions')
    op.drop_table('saved_payment_methods')
    # ### end Alembic commands ###
