"""add totp, sessions, payment methods, checkout policies, invoice footer

Revision ID: 33f037391660
Revises: c49ba13c510c
Create Date: 2026-07-17 20:51:47.693830

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '33f037391660'
down_revision = 'c49ba13c510c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_jti', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_jti')
    )
    op.add_column(
        'merchants',
        sa.Column(
            'enabled_payment_methods',
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text('\'["card", "wallet", "bank_transfer"]\'::jsonb'),
            nullable=False,
        ),
    )
    op.alter_column('merchants', 'enabled_payment_methods', server_default=None)
    op.add_column('merchants', sa.Column('checkout_terms_url', sa.String(length=2048), nullable=True))
    op.add_column('merchants', sa.Column('checkout_privacy_url', sa.String(length=2048), nullable=True))
    op.add_column('merchants', sa.Column('invoice_footer', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('totp_secret', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('totp_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('users', 'totp_enabled', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'totp_enabled')
    op.drop_column('users', 'totp_secret')
    op.drop_column('merchants', 'invoice_footer')
    op.drop_column('merchants', 'checkout_privacy_url')
    op.drop_column('merchants', 'checkout_terms_url')
    op.drop_column('merchants', 'enabled_payment_methods')
    op.drop_table('sessions')
    # ### end Alembic commands ###
