"""initial schema

Revision ID: 5fad243ed983
Revises: 
Create Date: 2026-07-16 07:49:35.883776

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5fad243ed983'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', name='merchant_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchants_email'), 'merchants', ['email'], unique=True)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('key_prefix', sa.String(length=32), nullable=False),
    sa.Column('hashed_key', sa.String(length=255), nullable=False),
    sa.Column('mode', sa.Enum('SANDBOX', 'LIVE', name='api_key_mode'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checkout_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PENDING', 'SUCCEEDED', 'FAILED', 'EXPIRED', 'CANCELLED', name='checkout_session_status'), nullable=False),
    sa.Column('method', sa.Enum('CARD', 'WALLET', 'BANK_TRANSFER', 'QR', name='payment_method'), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('customer_phone', sa.String(length=32), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('return_url', sa.String(length=2048), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('session_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount_minor > 0', name='ck_checkout_amount_positive'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'idempotency_key', name='uq_checkout_merchant_idempotency')
    )
    op.create_table('settlements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gross_amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('fee_amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('net_amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', name='settlement_status'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhook_endpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('secret', sa.String(length=255), nullable=False),
    sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('checkout_session_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('fee_minor', sa.BigInteger(), nullable=False),
    sa.Column('net_amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'AUTHORIZING', 'SUCCEEDED', 'FAILED', name='transaction_status'), nullable=False),
    sa.Column('gateway_reference', sa.String(length=64), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('payment_method_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('settled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['checkout_session_id'], ['checkout_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settlement_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('settlement_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhook_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('endpoint_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DELIVERED', 'FAILED', name='webhook_delivery_status'), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['webhook_endpoints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webhook_logs')
    op.drop_table('settlement_items')
    op.drop_table('transactions')
    op.drop_table('webhook_endpoints')
    op.drop_table('settlements')
    op.drop_table('checkout_sessions')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_merchants_email'), table_name='merchants')
    op.drop_table('merchants')
    # ### end Alembic commands ###
