"""add invoices, live access requests, merchant live status

Revision ID: 75a7e4a02514
Revises: e922bfbbd2b7
Create Date: 2026-07-16 14:43:23.357372

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '75a7e4a02514'
down_revision = 'e922bfbbd2b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_access_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('legal_business_name', sa.String(length=255), nullable=False),
    sa.Column('business_category', sa.String(length=120), nullable=False),
    sa.Column('registration_number', sa.String(length=120), nullable=True),
    sa.Column('website_url', sa.String(length=2048), nullable=True),
    sa.Column('bank_name', sa.String(length=120), nullable=False),
    sa.Column('bank_account_number', sa.String(length=64), nullable=False),
    sa.Column('contact_phone', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING_REVIEW', 'APPROVED', 'REJECTED', name='live_access_status'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'PAID', 'CANCELLED', name='invoice_status'), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checkout_session_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount_minor > 0', name='ck_invoice_amount_positive'),
    sa.ForeignKeyConstraint(['checkout_session_id'], ['checkout_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    merchant_live_status = postgresql.ENUM('SANDBOX_ONLY', 'PENDING_REVIEW', 'LIVE', name='merchant_live_status')
    merchant_live_status.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'merchants',
        sa.Column('live_status', merchant_live_status, nullable=False, server_default='SANDBOX_ONLY'),
    )
    op.alter_column('merchants', 'live_status', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchants', 'live_status')
    postgresql.ENUM(name='merchant_live_status').drop(op.get_bind(), checkfirst=True)
    op.drop_table('invoices')
    op.drop_table('live_access_requests')
    # ### end Alembic commands ###
