"""add users table and merchant business branding payout fields

Revision ID: 8a4c78556c99
Revises: 87f19387c2cf
Create Date: 2026-07-16 20:39:31.886956

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '8a4c78556c99'
down_revision = '87f19387c2cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'ANALYST', 'SUPPORT', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('INVITED', 'ACTIVE', 'SUSPENDED', name='user_status'), nullable=False),
    sa.Column('invite_token', sa.String(length=64), nullable=True),
    sa.Column('invite_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_token')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('merchants', sa.Column('support_email', sa.String(length=255), nullable=True))
    op.add_column('merchants', sa.Column('support_phone', sa.String(length=32), nullable=True))
    op.add_column('merchants', sa.Column('business_address', sa.String(length=500), nullable=True))
    op.add_column('merchants', sa.Column('business_website', sa.String(length=2048), nullable=True))
    op.add_column('merchants', sa.Column('statement_descriptor', sa.String(length=22), nullable=True))
    op.add_column('merchants', sa.Column('logo_url', sa.String(length=2048), nullable=True))
    op.add_column('merchants', sa.Column('brand_color', sa.String(length=7), nullable=True))
    op.add_column('merchants', sa.Column('payout_bank_name', sa.String(length=120), nullable=True))
    op.add_column('merchants', sa.Column('payout_bank_account_number', sa.String(length=64), nullable=True))
    payout_schedule = postgresql.ENUM('DAILY', 'WEEKLY', 'MONTHLY', name='payout_schedule')
    payout_schedule.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'merchants',
        sa.Column(
            'payout_schedule',
            payout_schedule,
            nullable=False,
            server_default='WEEKLY',
        ),
    )
    op.alter_column('merchants', 'payout_schedule', server_default=None)
    # ### end Alembic commands (table/column shape) ###

    # Data migration: every existing merchant becomes an OWNER user carrying
    # its old login credentials forward, before we drop merchants.password_hash.
    op.execute(
        """
        INSERT INTO users (id, merchant_id, email, password_hash, role, status, created_at)
        SELECT gen_random_uuid(), id, email, password_hash, 'OWNER', 'ACTIVE', now()
        FROM merchants
        """
    )

    op.drop_column('merchants', 'password_hash')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.execute(
        """
        UPDATE merchants
        SET password_hash = users.password_hash
        FROM users
        WHERE users.merchant_id = merchants.id AND users.role = 'OWNER'
        """
    )
    op.alter_column('merchants', 'password_hash', nullable=False)
    op.drop_column('merchants', 'payout_schedule')
    postgresql.ENUM(name='payout_schedule').drop(op.get_bind(), checkfirst=True)
    op.drop_column('merchants', 'payout_bank_account_number')
    op.drop_column('merchants', 'payout_bank_name')
    op.drop_column('merchants', 'brand_color')
    op.drop_column('merchants', 'logo_url')
    op.drop_column('merchants', 'statement_descriptor')
    op.drop_column('merchants', 'business_website')
    op.drop_column('merchants', 'business_address')
    op.drop_column('merchants', 'support_phone')
    op.drop_column('merchants', 'support_email')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    postgresql.ENUM(name='user_status').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='user_role').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
