"""add payment link id to checkout sessions

Revision ID: a8b28c4812c0
Revises: 8a4c78556c99
Create Date: 2026-07-16 21:27:27.752516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8b28c4812c0'
down_revision = '8a4c78556c99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkout_sessions', sa.Column('payment_link_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'checkout_sessions', 'payment_links', ['payment_link_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'checkout_sessions', type_='foreignkey')
    op.drop_column('checkout_sessions', 'payment_link_id')
    # ### end Alembic commands ###
