"""add price_id to payment_links

Revision ID: c49ba13c510c
Revises: 13d87b36157c
Create Date: 2026-07-17 14:15:19.520896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c49ba13c510c'
down_revision = '13d87b36157c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_links', sa.Column('price_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'payment_links', 'prices', ['price_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_links', type_='foreignkey')
    op.drop_column('payment_links', 'price_id')
    # ### end Alembic commands ###
